language: node_js

node_js:
  - 8

branches:
  only:
    - master

cache: yarn

env:
  global:
  # SLACK
  - secure: "meImGu82jF1iQPEcu4u2QbPTNbtQcsGoUK1NVa1uGeKyb205ephDdkfW4MqQwHfnTdkWf7s4i+NpwY/29XJvKYcsD12BIXkkHnwPx0T0wI+1EJs4iG692pLecBIaXqxBDTyhdBSUm32C17zW4nCWxszYlkKlKtJLsIJxx5JrKczKXv2KLC8ZRP3EWgrCCkjRIGb1keQ5iEHMGudCxJYXwcQVuMJvzokhCu3gaCksWbsk9kNitHKEmzz/gqNB2WD+ghIq7EPCVui1DMK/AYx/UIDHFDT1b3f2jviWrTVrOVeSF+fL7OzdWMEF03iy8t9bfR2SlTCyOyC/WM9i/hB+DHYj5Pgo//J8/s6wjHluH1RcASHAnzJ2epMQ2gp05aotkDAlRPBZnAZyMZI/+F15XcLvuqqTATv3T8LMS6NKkxDHSwuEWbR2Bjkg5noN4TcTP/7EqvMpm9Jowad//RlQYvpfZ3pt63NEk63t0OxVhtCB7eWu4gIgQLarYmd3CmkRhtf76resN3F1Mb7WRDhVbwRaCfXxx8DKfqjc1RPdD7pGcCP6zJVIR4yqXpQHuS7Fy0NM9gSCV8vDipmq/FayedcS49Wj/FrRZ6OVh8SxIx+3yGqT28eLBd21RmtR2Kdg2cgAwDa5w/PZipEpq5gj6IMwBFXZlYsSleWefbW2hDQ="
  # NPM
  - secure: "IP/aozOzrnmHwi/Jwshnuzo5rrAqhja31rvCLwz6H2ybKFUvg3iQKIbol/J2yZZ6mAqvKghZZa68+Frb9OItLvdGqXdSXlaH4li5yRLVtKtpuO/nE9r2zA9Dh/kxJ4hkPurkTTnDYkIBvpu60QsOv6HeoN+CovcOol9JGCDUrI3JMLDcaPxcIVnky4l+FA2+6RgD9QNi2xigHF04pf9VqdHGu+ZMeyHWcnb0aP/tCT8hxAXEAce1pE4WNaz0gcJOaS0OVZlPvycvywVwEEGxn/4D5EgNaB19oQ05vFfO46/RPiqSbDj8RupQcyT/UN4QzfOv4JvW+fX1Uks9duvfNTMDxXseZ/McM1gddCPQDHyJmzlqIOVC5yMSpf+6lXKwTTwvZUZxF0V1vcRkySu2nXoZhLd1xEcdsN89IwxjFerHS5eLGYPfHUOny5J8K4rjFJdhcNry3ag0MXUDuM28ur68P4zguEThbm7RBaQTRJZYgHdqIV4YMqC+1ZdNCKTnKRBnN34bETsdnGrcFicAqXti1imjc4iXVm3lkARsS3N5dd1hRVuQ6whXHk7CDj/8BIJjnU9WtfjSUKSWoX2K7rpp/8ysPefb5hD/sRt80NWN/6n4TeZe6h7HSPsXwMjUqWkfQSZBZAZUHNQH7v1h8SB53iEuEKI3tzrSz35bgRA="
  # GITHUB
  - secure: "arESY2tt0yyhtuYUe1/DQXgF38ypA7q0G2CwKpXzv7FWZU9We4/s0HsotLp07qMosRGiBrxseVMRPKSpNN8PuGkPu348TtDSouR+b9UvXEjuD++priAqaQzRIvt5krgq7K3KNM+o67m/RWBU0WWapm4t1jusNKAtz7GA5ERLkdDCHkc0Y6KPNv28sowxey/klEwS1BlJAXA5VN0+eyyMj8UnLXxMQEnYy+vfCIGTic3Qe1j7YhSeezGevo6uhtBLQCVwxYhwQfwQuH7h8PULxw0jhTEN6ciIqr9p4jw1HOWVIkLkZHcnPWgOtmkSU88TGhZo/215+j2+9/aN/Gk1U5PRwK7e7ztmBbV6YDHljlT9M/pAMJjIUC18Tq79Vkurdlq5K6lcU/CULofzzhpm9GpuHIURb6rvrTOA7Xn2QbLgeYjptrR4PUZmY/KMTDk+VN4mF4hJHtTk2CpReY0xAlOaGjv0S5xZfwV+RrNH4lA2yQvTNzW/lKmRZsiAXl9Juu12COifLIgJsk3XbsltJ4BK7az+IRV0HXnslUFAIJtfD2laS1YI3o25dTWqv17JtW32wD/ph127skGmK+oJc1JRzWB6Jw+ctWdFZR3AyRLJp3TF/M4tTslTSaKJD/ZoTEp/OFd+3ln9iZHBMma/oHUnKzClqgAmj37SH40INWc="

before_install:
  - echo "//registry.npmjs.com/:_authToken=\${NPM_TOKEN}" > .npmrc
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

script:
  - make travis

after_script:
  - tc-builder slack-notify
